import { BadgeCheck, FileText, HelpCircle, Sparkles } from "lucide-react";

import { cn } from "@/lib/utils";
import type { DateKind } from "@/domain/types";

export const DATE_KIND_LABEL: Record<DateKind, string> = {
  official: "Official date",
  document: "From your document",
  reminder: "Stay Valid reminder",
  needs_confirmation: "Needs confirmation",
};

export const DATE_KIND_HELP: Record<DateKind, string> = {
  official: "Stated or computed directly from a government source in the corpus.",
  document: "A date you typed in from your own paperwork.",
  reminder: "A preparation reminder generated by Stay Valid. Not a government deadline.",
  needs_confirmation:
    "Depends on a rule that is not yet in force, delayed or uncertain. Confirm with your DSO.",
};

const STYLES: Record<DateKind, string> = {
  official: "bg-teal-soft text-attn-monitor border-teal/40",
  document: "bg-muted text-muted-foreground border-border",
  reminder: "bg-amber-soft text-attn-prepare border-amber/40",
  needs_confirmation: "bg-attn-confirm-soft text-attn-confirm border-attn-confirm/30",
};

const ICONS: Record<DateKind, typeof BadgeCheck> = {
  official: BadgeCheck,
  document: FileText,
  reminder: Sparkles,
  needs_confirmation: HelpCircle,
};

export function DateKindBadge({ kind, className }: { kind: DateKind; className?: string }) {
  const Icon = ICONS[kind];
  return (
    <span
      className={cn(
        "inline-flex items-center gap-1.5 rounded-md border px-2 py-0.5 text-[11px] font-semibold",
        STYLES[kind],
        className,
      )}
    >
      <Icon aria-hidden="true" className="size-3" />
      {DATE_KIND_LABEL[kind]}
    </span>
  );
}
